# Generated by Django 4.2.6 on 2023-11-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champions_League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('champion', models.CharField(max_length=250)),
                ('runner_up', models.CharField(max_length=250)),
                ('best_player', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Copa_Libertadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('champion', models.CharField(max_length=250)),
                ('runner_up', models.CharField(max_length=250)),
                ('best_player', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Copa_Sudamericana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('champion', models.CharField(max_length=250)),
                ('runner_up', models.CharField(max_length=250)),
                ('best_player', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
