# Generated by Django 4.2.6 on 2023-11-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copa_sudamericana',
            old_name='champion',
            new_name='capitan',
        ),
        migrations.RenameField(
            model_name='copa_sudamericana',
            old_name='runner_up',
            new_name='director_tecnico',
        ),
        migrations.RenameField(
            model_name='copa_sudamericana',
            old_name='season',
            new_name='dorsal',
        ),
        migrations.RenameField(
            model_name='copa_sudamericana',
            old_name='continent',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='copa_sudamericana',
            name='best_player',
        ),
    ]
