# Generated by Django 4.2.6 on 2023-11-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_rename_champion_copa_sudamericana_capitan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copa_sudamericana',
            old_name='nombre',
            new_name='equipo',
        ),
    ]
